version: '2'
services:
    jegues-app:
        image: jegues
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jegues-postgresql:5432/jegues
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jegues-postgresql:
        extends:
            file: postgresql.yml
            service: jegues-postgresql
