version: '2'
services:
    jegues-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jegues/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jegues
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
